### ISSUE TITLE
Not an issue just don’t know how to inbox?

### ISSUE THREAD

**Issue by Dicksurfer** [camden-smallwood/solidity-rs#2]
Camden, it’s Ali. I had a horrible nightmare and just want to know you’re okay. I’ve spent all morning trying to find a way to reach you and went as far as to sign up for whatever this is??? I genuinely just want to know you’re okay because I keep having this nightmare and I just want to know it’s not true. Dicksurfer is my username on most things. Aleczandria on Facebook. 2541693 with the same area code as always.

**Comment by iFrostizz** [comment]
Hey sir, very nice work !
I was building the exact same tool, with pluggable "modules" instead of analysers, and using ethers-solc from the ethers-rs repo to compile projects and get the ast from that before I found out your work.
Do you plan to move on to ethers-solc to make it more modular ? Like as it already handles hardhat & foundry/dapptools you wouldn't have to handle this logic, and it would also even work for every contracts in a specific directory without too much overhead.
Have a nice day sir
